### PR TITLE
Duplicate guard soft failure grading

### LINKED ISSUE #68: Preserve structured MCP error-kind through the tool wrapper chain
## Problem

`mcp_response.rs::extract_tool_result` stringifies every MCP response before it reaches the tool wrapper chain. For error responses, the function collapses schema-validation failures, rate limits, timeouts, and server-internal errors into a single opaque string class prefixed with `"Tool returned an error: "`. Downstream consumers that need to make semantics-aware decisions have no structured signal to work with.

## Solution

Introduced `CallOutcome` enum (`Success` / `SchemaError` / `GeneralToolError`) in `crates/aura/src/mcp_response.rs`. Threaded through `ToolWrapper::transform_output` so downstream consumers can branch structurally instead of parsing string prefixes. Existing callers use `into_prefixed_string()` for backward compatibility.

## Related code

- `crates/aura/src/mcp_response.rs` — `CallOutcome` enum and `extract_tool_result`
- `crates/aura/src/tool_wrapper.rs` — `transform_output` signature carries `&CallOutcome`
- `crates/aura/src/mcp_streamable_http.rs` — callers use `into_prefixed_string()` at boundary

### PR DESCRIPTION
**Pull request by Shearerbeard**
Enhanced the looping guard to explicitly fail dependent worker tasks and give a clearer signal to the coordinator as to why a task was force killed. Also opens up the plumbing for other worker escalates to coordinator workflows.

closes #68 #69 #70 

LOG-23734
LOG-23735
LOG-23743

### CODE REVIEW

File: crates/aura/src/orchestration/orchestrator.rs [hunk 1]
```diff
@@ -469,11 +473,14 @@ impl Orchestrator {
             self.tool_call_observer.clone(),
             task_id,
         ));
-        let max_dup = self
-            .config
-            .max_consecutive_duplicate_tool_calls
-            .unwrap_or(1);
-        let duplicate_guard = Arc::new(DuplicateCallGuard::new(max_dup));
+        let nudge = self.config.duplicate_call_nudge_threshold.unwrap_or(3);
+        let block = self.config.duplicate_call_block_threshold.unwrap_or(5);
```
Comment (dominic-mcallister-logdna) [inline crates/aura/src/orchestration/orchestrator.rs]: Instead of defining the default of 3 or 5 here, we can do so on the struct itself?

Comment (Shearerbeard) [reply crates/aura/src/orchestration/orchestrator.rs]: Good call and yes.

**Review by dominic-mcallister-logdna — APPROVED** [review]
